### ISSUE TITLE
MethodInjector not working

### ISSUE THREAD

**Issue by mylemans** [ash47/TheyAreBillionsModKit#1]
I had a look at the MethodInjector, but it seems to not work.

When you try to launch it, it launches it, but then it stops and launches through Steam instead.

How did you get this to work?

**Comment by ash47** [comment]
Fixed up some debug code I had committed, give this version a try and let me know?

https://github.com/ash47/TheyAreBillionsModKit/releases/tag/0.03

**Comment by mylemans** [comment]
That works, thanks :)

**Comment by ash47** [comment]
Neat, let me know what you think :)
